from scsr.models.elements import ElementAO, ElementReferenceAO

def create_element(enName,ptName,refer):
    el=ElementAO()
    el.add_name('en',enName)
    el.add_name('pt',ptName)
    el.save()# TODO: Create the ElementReference representation and code the reference adding here.
    er=ElementReferenceAO.get_reference(el)
    er.set_reference(refer)
    er.save()

def start_pigd():   
    create_element("Abilities","Habilidades",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Abilities"})
    create_element("Ability Losses","Perda de Habilidades",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Ability_Losses"})
    create_element("Abstract Player Construct Development","Desenvolvimento por Construções Abstradas de Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Abstract_Player_Construct_Development"})
    create_element("Abstract Player Constructs","Construções Abstratas de Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Abstract_Player_Constructs"})
    create_element("Access Rewards","Recompensas de Acesso",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Access_Rewards"})
    create_element("Achievements","Alcances (Achievements)",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Achievements"})
    create_element("Achilles' Heels","Calcanhar de Aquiles",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Achilles%27_Heels"})
    create_element("Action Caps","Limite de Ações",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Action_Caps"})
    create_element("Action Programming","Programação de Ação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Action_Programming"})
    create_element("Actions Have Diegetically Social Consequences","Ações de Consequências Diegeticamente Sociais",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Actions_Have_Diegetically_Social_Consequences"})
    create_element("Actor Detachment","Desacoplamento de Ator",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Actor_Detachment"})
    create_element("Adventures","Aventuras",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Adventures"})
    create_element("Agents","Agentes",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Agents"})
    create_element("AI Players","Jogadores IA",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/AI_Players"})
    create_element("Aim &amp; Shoot","Mirar e Atirar",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Aim_%26_Shoot"})
    create_element("Alarms","Alarmes",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Alarms"})
    create_element("Algorithmic Agents","Agentes Algoritmicos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Algorithmic_Agents"})
    create_element("Alien Space Bats","Alien Space Bats",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Alien_Space_Bats"})
    create_element("Alignment","Alinhamento",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Alignment"})
    create_element("Alternate Reality Gameplay","Jogo de Realidade Alternada",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Alternate_Reality_Gameplay"})
    create_element("Altruistic Actions","Ações Altruísticas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Altruistic_Actions"})
    create_element("Always Vulnerable","Sempre Vulnerável",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Always_Vulnerable"})
    create_element("Ambiguous Responses","Respostas Ambíguas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Ambiguous_Responses"})
    create_element("Ammunition","Munição",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Ammunition"})
    create_element("Analysis Paralysis","Paralisia para Análise",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Analysis_Paralysis"})
    create_element("Anonymous Actions","Ações Anônimas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Anonymous_Actions"})
    create_element("Area Control","Controle de Área",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Area_Control"})
    create_element("Arenas","Arenas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Arenas"})
    create_element("Arithmetic Progression","Progressão Aritmética",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Arithmetic_Progression"})
    create_element("Armor","Armadura",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Armor"})
    create_element("Artifact-Location Proximity","Localização Proximidade de Artefato",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Artifact-Location_Proximity"})
    create_element("Asymmetric Gameplay","Jogabilidade Assimétrica",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Asymmetric_Gameplay"})
    create_element("Asymmetric Goals","Objetivos Assimétricos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Asymmetric_Goals"})
    create_element("Asymmetric Starting Conditions","Condições Assimétricas de Início",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Asymmetric_Starting_Conditions"})
    create_element("Asynchronous Collaborative Actions","Ações Colaborativas Assíncronas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Asynchronous_Collaborative_Actions"})
    create_element("Asynchronous Gameplay","Jogabilidade Assíncrona",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Asynchronous_Gameplay"})
    create_element("Attention Demanding Gameplay","Jogabilidade Demanda Atenção",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Attention_Demanding_Gameplay"})
    create_element("Auto-Aim","Auto-Mira",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Auto-Aim"})
    create_element("Auxiliary Game Screens","Telas de Jogo Auxiliares",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Auxiliary_Game_Screens"})
    create_element("Avatars","Avatares",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Avatars"})
    create_element("Awareness of Surroundings","Percepção da Localidade",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Awareness_of_Surroundings"})
    create_element("Back-to-Back Game Sessions","Jogo de Volta",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Back-to-Back_Game_Sessions"})
    create_element("Backseat Gamers","Torcida",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Backseat_Gamers"})
    create_element("Backtracking Levels","Níveis de Retorno",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Backtracking_Levels"})
    create_element("Bag Building","Bag Building",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Bag_Building"})
    create_element("Bag Management","Bag Management",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Bag_Management"})
    create_element("Balancing Effects","Efeitos de Balanceamento",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Balancing_Effects"})
    create_element("Bases","Bases",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Bases"})
    create_element("Beat the Leader","Derrote o Líder",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Beat_the_Leader"})
    create_element("Betrayal","Traição",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Betrayal"})
    create_element("Betting","Aposta",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Betting"})
    create_element("Bidding","Aposta Inicial",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Bidding"})
    create_element("Big Dumb Objects","Objetos Grandiosos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Big_Dumb_Objects"})
    create_element("Bluffing","Blefe",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Bluffing"})
    create_element("Bookkeeping Tokens","Elementos de Indicação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Bookkeeping_Tokens"})
    create_element("Boss Monsters","Monstros Principais",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Boss_Monsters"})
    create_element("Budgeted Action Points","Pontos de Ação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Budgeted_Action_Points"})
    create_element("Cameras","Câmeras",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Cameras"})
    create_element("Campaigns","Campanhas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Campaigns"})
    create_element("Camping","Acampar",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Camping"})
    create_element("Card Building","Construção de Carta",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Card_Building"})
    create_element("Cards","Cartas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Cards"})
    create_element("Casual Gameplay","Jogabilidade Casual",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Casual_Gameplay"})
    create_element("Challenging Gameplay","Jogabilidade Desafiadora",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Challenging_Gameplay"})
    create_element("Changes in Perception of Real World Phenomena due to Gameplay","Mudanças da Percepção de Fenômenos do Mundo Real devido à Jogabilidade",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Changes_in_Perception_of_Real_World_Phenomena_due_to_Gameplay"})
    create_element("Character Alignments","Alinhamento de Personagens",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Character_Alignments"})
    create_element("Character Defining Actions","Ações Definidas Por Personagens",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Character_Defining_Actions"})
    create_element("Character Development","Desenvolvimento de Personagem",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Character_Development"})
    create_element("Character Levels","Nível de Personagem",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Character_Levels"})
    create_element("Characteristics","Caracerísticas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Characteristics"})
    create_element("Characters","Personagens",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Characters"})
    create_element("Chargers","Recarregadores",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Chargers"})
    create_element("Chat Channels","Canais de Chat",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Chat_Channels"})
    create_element("Choke Points","Pontos de Obstáculos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Choke_Points"})
    create_element("Clickability","Clicabilidade",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Clickability"})
    create_element("Closure Points","Pontos de Fechamento",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Closure_Points"})
    create_element("Clues","Dicas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Clues"})
    create_element("Coaches","Treinadores",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Coaches"})
    create_element("Collaborative Actions","Ações Colaborativas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Collaborative_Actions"})
    create_element("Collectible Card Games","Jogos de Cartas Colecionáveis",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Collectible_Card_Games"})
    create_element("Combat","Combate",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Combat"})
    create_element("Combos","Combinações de Ações",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Combos"})
    create_element("Committed Goals","Objetivos Comprometidos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Committed_Goals"})
    create_element("Communication Channels","Canais de Comunicação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Communication_Channels"})
    create_element("Companion Quests","Tarefas de Acompanhantes",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Companion_Quests"})
    create_element("Companions","Acompanhantes",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Companions"})
    create_element("Competence Areas","Áreas de Competência",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Competence_Areas"})
    create_element("Complete Resource Depletion","Esgotamento Total de Recurso",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Complete_Resource_Depletion"})
    create_element("Complex Gameplay","Jogabilidade Complexa",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Complex_Gameplay"})
    create_element("Conceal","Ocultar Informações",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Conceal"})
    create_element("Conditional Passageways","Passagens Condicionais",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Conditional_Passageways"})
    create_element("Configurable Gameplay Areas","Áreas de Jogabilidade Configurável",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Configurable_Gameplay_Areas"})
    create_element("Configuration","Configuração",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Configuration"})
    create_element("Construction","Construção",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Construction"})
    create_element("Construction/Scoring Phase Shift","Deslocamento de Fases Construção/Pontuação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Construction/Scoring_Phase_Shift"})
    create_element("Context Dependent Reactions","Reações Dependentes de Contexto",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Context_Dependent_Reactions"})
    create_element("Contextualization","Contextualização",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Contextualization"})
    create_element("Contextualized Conversational Responses","Respostas Contextualizadas de Conversação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Contextualized_Conversational_Responses"})
    create_element("Continuous Goals","Objetivos Contínuos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Continuous_Goals"})
    create_element("Controllers","Controles",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Controllers"})
    create_element("Cooldown","Cooldown",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Cooldown"})
    create_element("Cooperation","Cooperação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Cooperation"})
    create_element("Cosmetic Game Items","Itens Cosméticos de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Cosmetic_Game_Items"})
    create_element("Coupled Games","Jogos Acoplados",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Coupled_Games"})
    create_element("Crafting","Crafting",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Crafting"})
    create_element("Critical Failures","Falhas Críticas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Critical_Failures"})
    create_element("Critical Gameplay Design","Design de Jogabilidade Crítico",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Critical_Gameplay_Design"})
    create_element("Critical Hits","Acertos Críticos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Critical_Hits"})
    create_element("Critical Misses","Erros Críticos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Critical_Misses"})
    create_element("Critical Results","Resultados Críticos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Critical_Results"})
    create_element("Critical Successes","Sucessos Críticos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Critical_Successes"})
    create_element("Crosshairs","Mira",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Crosshairs"})
    create_element("Crossmedia Gameplay","Jogabilidade entre Mídias",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Crossmedia_Gameplay"})
    create_element("Current Player Tokens","Token de Jogador Corrente",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Current_Player_Tokens"})
    create_element("Cutscenes","Cutscenes",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Cutscenes"})
    create_element("Cycle Deck Engines","Cycle Deck Engines",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Cycle_Deck_Engines"})
    create_element("Damage","Dano",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Damage"})
    create_element("Death Consequences","Consequências de Morte",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Death_Consequences"})
    create_element("Deck Building","Construção de Deck",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Deck_Building"})
    create_element("Decks","Decks",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Decks"})
    create_element("Decreased Abilities","Diminuição de Habilidades",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Decreased_Abilities"})
    create_element("Dedicated Game Facilitators","Facilitadores de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Dedicated_Game_Facilitators"})
    create_element("Delayed Effects","Efeitos Atrasados",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Delayed_Effects"})
    create_element("Delayed Reciprocity","Reciprocidade Atrasada",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Delayed_Reciprocity"})
    create_element("Destructible Objects","Objetos Destrutíveis",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Destructible_Objects"})
    create_element("Detective Structures","Estruturas Detetive",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Detective_Structures"})
    create_element("Deterioration","Deterioração",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Deterioration"})
    create_element("Determinable Chance to Succeed","Chance de Sucesso Determinável",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Determinable_Chance_to_Succeed"})
    create_element("Development Time","Tempo de Desenvolvimento",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Development_Time"})
    create_element("Dexterity-Based Actions","Ações Baseadas em Destreza",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Dexterity-Based_Actions"})
    create_element("Dialogues","Diálogos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Dialogues"})
    create_element("Dice","Dados",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Dice"})
    create_element("Diegetic Communication","Comunicação Diegética",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Diegetic_Communication"})
    create_element("Diegetic Consistency","Consistência Diegética",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Diegetic_Consistency"})
    create_element("Diegetically Outstanding Features","Características Diegeticamente Marcantes",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Diegetically_Outstanding_Features"})
    create_element("Diegetically Tangible Game Items","Itens de Jogo Diegeticamente Tangíveis",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Diegetically_Tangible_Game_Items"})
    create_element("Difficulty Levels","Níveis de Dificuldade",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Difficulty_Levels"})
    create_element("Discard Piles","Pilhas de Descarte",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Discard_Piles"})
    create_element("Downtime","Downtime",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Downtime"})
    create_element("Drafting","Elaboração",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Drafting"})
    create_element("Drafting Spreads","Elaborações Possíveis",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Drafting_Spreads"})
    create_element("Drawing Stacks","Pilha de Retirada",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Drawing_Stacks"})
    create_element("Drop-In/Drop-Out","Entrada/Saida em Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Drop-In/Drop-Out"})
    create_element("Dynamic Goal Characteristics","Características Dinâmicas de Objetivo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Dynamic_Goal_Characteristics"})
    create_element("Early Elimination","Eliminação Adiantada",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Early_Elimination"})
    create_element("Early Leaving Players","Desistência",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Early_Leaving_Players"})
    create_element("Easter Eggs","Easter Eggs",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Easter_Eggs"})
    create_element("Eliminate","Eliminação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Eliminate"})
    create_element("Emotes","Emotes",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Emotes"})
    create_element("Emotional Attachment","Ligação Emocional",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Emotional_Attachment"})
    create_element("Enactment","Atuação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Enactment"})
    create_element("Enclosure","Cerco",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Enclosure"})
    create_element("Encouraged Return Visits","Encorajamento de Retorno",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Encouraged_Return_Visits"})
    create_element("End State Scoring","Pontuação Final",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/End_State_Scoring"})
    create_element("Endgame","Final do Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Endgame"})
    create_element("Endgame Quests","Quest de Final do Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Endgame_Quests"})
    create_element("Enemies","Inimigos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Enemies"})
    create_element("Energy Penalties","Penalties de Energia",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Energy_Penalties"})
    create_element("Enforced Agent Behavior","Comportamento de Agente Forçado",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Enforced_Agent_Behavior"})
    create_element("Enforced Player Anonymity","Anonimidade Forçada ao Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Enforced_Player_Anonymity"})
    create_element("Entitled Players","Jogadores Responsáveis",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/En_Players"})
    create_element("Entrenching Gameplay","Jogabilidade Limitante",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Entrenching_Gameplay"})
    create_element("Environmental Effects","Efeitos Ambientais",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Environmental_Effects"})
    create_element("Environmental Storytelling","Storytelling Ambiental",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Environmental_Storytelling"})
    create_element("Ephemeral Events","Eventos Efêmeros",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Ephemeral_Events"})
    create_element("Ephemeral Goals","Objetivos Efêmeros",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Ephemeral_Goals"})
    create_element("Equipment","Equipamento",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Equipment"})
    create_element("Equipment Slots","Espaço de Equipamento",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Equipment_Slots"})
    create_element("Events Timed to the Real World","Eventos Sincronizados com o Mundo Real",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Events_Timed_to_the_Real_World"})
    create_element("Ever Increasing Difficulty","Dificuldade Sempre Crescente",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Ever_Increasing_Difficulty"})
    create_element("Evolving Rule Sets","Conjunto Evolutivo de Regras",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Evolving_Rule_Sets"})
    create_element("Exaggerated Perception of Influence","Percepção Exagerada de Influência",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Exaggerated_Perception_of_Influence"})
    create_element("Exceptional Events","Eventos Excepcionais",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Exceptional_Events"})
    create_element("Excise","Excise",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Excise"})
    create_element("Excluding Goals","Objetivos Excludentes",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Excluding_Goals"})
    create_element("Expansion","Expansão",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Expansion"})
    create_element("Experimenting","Experimentação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Experimenting"})
    create_element("Explicit Random Seeds","Sementes Aleatórias Explícitas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Explicit_Random_Seeds"})
    create_element("Exploitation","Exploração",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Exploitation"})
    create_element("Extended Actions","Ações Extentidas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Extended_Actions"})
    create_element("Extermination","Exterminação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Extermination"})
    create_element("Extra Chances","Chances Extras",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Extra_Chances"})
    create_element("Extra Turns","Turnos Extra",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Extra_Turns"})
    create_element("Extra-Game Actions","Ações de Jogo Extra",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Extra-Game_Actions"})
    create_element("Extra-Game Broadcasting","Transmissão do Jogo ao Exterior",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Extra-Game_Broadcasting"})
    create_element("Extra-Game Consequences","Consequências Extra Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Extra-Game_Consequences"})
    create_element("Extra-Game Input","Entrada Extra Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Extra-Game_Input"})
    create_element("Facilitating Rewards","Facilitadores de Recompensas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Facilitating_Rewards"})
    create_element("Factions","Facções",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Factions"})
    create_element("Fake Game Cancellations","Cancelações Falsas de Jogos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Fake_Game_Cancellations"})
    create_element("Fake Game Overs","Fim de Jogo Falso",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Fake_Game_Overs"})
    create_element("Feelies","Brindes",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Feelies"})
    create_element("Feigned Die Rolls","Rolagem de Dados Falsa",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Feigned_Die_Rolls"})
    create_element("Finale Levels","Níveis Finais",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Finale_Levels"})
    create_element("First Player Advantages","Vantagem de Primeiro Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/First_Player_Advantages"})
    create_element("First Player Tokens","Tokens de Primeiro Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/First_Player_Tokens"})
    create_element("First-Person Views","Visão em Primeira Pessoa",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/First-Person_Views"})
    create_element("Fixed Distributions","Distribuições Fixas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Fixed_Distributions"})
    create_element("Flanking Routes","rotas Flanqueantes",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Flanking_Routes"})
    create_element("Flip-Flop Events","Eventos Flip-Flop",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Flip-Flop_Events"})
    create_element("Focus Loci","Focus Loci",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Focus_Loci"})
    create_element("Fog of War","Fog of War",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Fog_of_War"})
    create_element("Framed Freedom","Framed Freedom",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Framed_Freedom"})
    create_element("Free Game Element Manipulation","Manipulação Livre de Elementos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Free_Game_Element_Manipulation"})
    create_element("Free Gift Inventories","Inventário Livre para Presentes",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Free_Gift_Inventories"})
    create_element("Freedom of Choice","Liberdade de Escolha",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Freedom_of_Choice"})
    create_element("Friend Lists","Lista de Amigos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Friend_Lists"})
    create_element("Friendly Fire","Fogo Amigo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Friendly_Fire"})
    create_element("FUBAR Enjoyment","Tensão Apreciada",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/FUBAR_Enjoyment"})
    create_element("Fudged Results","Resultados Manipulados",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Fudged_Results"})
    create_element("Functional Roles","Papéis Funcionais",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Functional_Roles"})
    create_element("Further Player Improvement Potential","Potencial de Melhoria do Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Further_Player_Improvement_Potential"})
    create_element("Gain Competence","Ganho de Competência",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Gain_Competence"})
    create_element("Gain Information","Ganho de Informação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Gain_Information"})
    create_element("Gain Ownership","Ganho de Propriedade",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Gain_Ownership"})
    create_element("Galleries","Galleria",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Galleries"})
    create_element("Game Boards","Tabuleiro",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_Boards"})
    create_element("Game Element Insertion","Inserção de Elemento de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_Element_Insertion"})
    create_element("Game Element Trading","Troca de Elemento de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_Element_Trading"})
    create_element("Game Instance Stories","Histórias de Instância de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_Instance_Stories"})
    create_element("Game Items","Itens de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_Items"})
    create_element("Game Lobbies","Lobbies de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_Lobbies"})
    create_element("Game Masters","Mestre de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_Masters"})
    create_element("Game Over","Fim de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_Over"})
    create_element("Game Pauses","Pausa de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_Pauses"})
    create_element("Game Servers","Servidor de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_Servers"})
    create_element("Game State Indicators","Indicador de Estado do Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_State_Indicators"})
    create_element("Game State Overviews","Resumo de Estado do JOgo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_State_Overviews"})
    create_element("Game System Player","Jogador do Sistema de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_System_Player"})
    create_element("Game Termination Penalties","Penalidades Terminais de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_Termination_Penalties"})
    create_element("Game Time Manipulation","Manipulação do Tempo do Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_Time_Manipulation"})
    create_element("Game World Exploration","Exploração do Mundo do Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_World_Exploration"})
    create_element("Game World Navigation","Navegação do Mundo do Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_World_Navigation"})
    create_element("Game Worlds","Mundo do Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Game_Worlds"})
    create_element("Gameplay Engines","Engine de Gameplay",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Gameplay_Engines"})
    create_element("Gameplay Mastery","Maestria de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Gameplay_Mastery"})
    create_element("Gameplay Statistics","Estatística de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Gameplay_Statistics"})
    create_element("Gamer Mode","Modo Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Gamer_Mode"})
    create_element("Generic Adversaries","Adversário Genérico",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Generic_Adversaries"})
    create_element("Geometric Progression","Progressão Geométrica",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Geometric_Progression"})
    create_element("Geospatial Game Widgets","Indicadores Geoespaciais",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Geospatial_Game_Widgets"})
    create_element("Ghosts","Fantasmas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Ghosts"})
    create_element("Goal Achievements","Alcances de Objetivo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Goal_Achievements"})
    create_element("Goal Hierarchies","Hierarquia de Objetivos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Goal_Hierarchies"})
    create_element("Goal Indicators","Indicadores de Objetivos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Goal_Indicators"})
    create_element("Goal-Driven Personal Development","Objetivo Dirigido a Desenvolvimento Pessoal",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Goal-Driven_Personal_Development"})
    create_element("God Fingers","God Fingers",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/God_Fingers"})
    create_element("God Views","Visão Completa",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/God_Views"})
    create_element("Gossip","Rumores",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Gossip"})
    create_element("Grind Achievements","Mineirar Alcances",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Grind_Achievements"})
    create_element("Grinding","Mineirar",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Grinding"})
    create_element("Guard","Guardar",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Guard"})
    create_element("Guilting","Culpabilidade",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Guilting"})
    create_element("Handicap Achievements","Alcances Limítrofes",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Handicap_Achievements"})
    create_element("Handicap Systems","Sistemas de Limitação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Handicap_Systems"})
    create_element("Handles","Indicadores",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Handles"})
    create_element("Hands","Mão",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Hands"})
    create_element("Health","Saúde",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Health"})
    create_element("Helpers","Ajudantes",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Helpers"})
    create_element("Helplessness","Desamparo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Helplessness"})
    create_element("Herd","Herd",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Herd"})
    create_element("Heterogeneous Game Element Ownership","Propriedade Heterogênea de Elementos de Jogos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Heterogeneous_Game_Element_Ownership"})
    create_element("Hiding Places","Esconderijos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Hiding_Places"})
    create_element("High Score Lists","Lista de High Score",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/High_Score_Lists"})
    create_element("Higher-Level Closures as Gameplay Progresses","Resoluções Niveladas Diretamente ao Progresso do Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Higher-Level_Closures_as_Gameplay_Progresses"})
    create_element("Hotseating","Troca de Jogador Corrente",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Hotseating"})
    create_element("Hovering Closures","Expectativas de Resoluções",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Hovering_Closures"})
    create_element("Hybrid Gameplay Spaces","Espaços Híbridos de Jogabilidade",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Hybrid_Gameplay_Spaces"})
    create_element("Illusion of Open Space","Ilusão de Espaço Aberto",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Illusion_of_Open_Space"})
    create_element("Illusionary Rewards","Recompensas Ilusórias",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Illusionary_Rewards"})
    create_element("Improved Abilities","Habilidades Melhoradas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Improved_Abilities"})
    create_element("Inaccessible Areas","Áreas Inacessíveis",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Inaccessible_Areas"})
    create_element("Incompatible Goals","Objetivos Incompatíveis",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Incompatible_Goals"})
    create_element("Increasing Rewards","Melhoria em Recompensas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Increasing_Rewards"})
    create_element("Individual Penalties","Penalidades Individuais",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Individual_Penalties"})
    create_element("Individual Rewards","Recompensas Individuais",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Individual_Rewards"})
    create_element("Information Passing","Troca de Informações",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Information_Passing"})
    create_element("Initiative","Iniciativa",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Initiative"})
    create_element("Installations","Instalações",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Installations"})
    create_element("Instances","Instâncias",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Instances"})
    create_element("Interferable Goals","Objetivos que se Interferem",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Interferable_Goals"})
    create_element("Internal Conflicts","Conflitos Internos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Internal_Conflicts"})
    create_element("Internal Rivalry","Rivalidade Interna",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Internal_Rivalry"})
    create_element("Interruptibility","Interruptibilidade",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Interruptibility"})
    create_element("Interruptible Actions","Ações Interruptíveis",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Interruptible_Actions"})
    create_element("Inventories","Inventário",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Inventories"})
    create_element("Investments","Investimentos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Investments"})
    create_element("Invisible Walls","Paredes Invisíveis",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Invisible_Walls"})
    create_element("Invites","Convites",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Invites"})
    create_element("Invulnerabilities","Invulnerabilidades",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Invulnerabilities"})
    create_element("Irreversible Events","Eventos Irreversíveis",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Irreversible_Events"})
    create_element("Killcams","Killcams",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Killcams"})
    create_element("Kingmaker","Kingmaker",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Kingmaker"})
    create_element("Landmarks","Ponto de Referência",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Landmarks"})
    create_element("Laning","Canalização de Movimento",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Laning"})
    create_element("Last Man Standing","Último em Pé",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Last_Man_Standing"})
    create_element("Late Arriving Players","Jogadores Tardios",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Late_Arriving_Players"})
    create_element("Legacy Games","Jogos Legados",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Legacy_Games"})
    create_element("Life Penalties","Penalidades de Vida",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Life_Penalties"})
    create_element("Line of Sight","Linha de Visão",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Line_of_Sight"})
    create_element("Live Action Roleplaying","Live Action Roleplaying",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Live_Action_Roleplaying"})
    create_element("Loading Hints","Dicas em Carregamento",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Loading_Hints"})
    create_element("Location-Fixed Abilities","Habilidades Específica de Localização",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Location-Fixed_Abilities"})
    create_element("Loot","Loot",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Loot"})
    create_element("Loyalty","Lealdade",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Loyalty"})
    create_element("Luck","Sorte",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Luck"})
    create_element("Lucky Guess Solutions","Soluções Baseadas em Sorte",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Lucky_Guess_Solutions"})
    create_element("Lull Periods","Calmaria",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Lull_Periods"})
    create_element("MacGuffins","MacGuffins",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/MacGuffins"})
    create_element("Main Quests","Buscas Principais",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Main_Quests"})
    create_element("Maneuvering","Manobragem",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Maneuvering"})
    create_element("Massively Multiplayer Online Games","Massively Multiplayer Online Games",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Massively_Multiplayer_Online_Games"})
    create_element("Massively Single-Player Online Games","Massively Single-Player Online Games",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Massively_Single-Player_Online_Games"})
    create_element("Mediated Gameplay","Jogabilidade Mediada",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Mediated_Gameplay"})
    create_element("Melodramatic Structures","Estruturas Melodramáticas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Melodramatic_Structures"})
    create_element("Memorabilia","Memorabilia",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Memorabilia"})
    create_element("Memorizing","Memorização",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Memorizing"})
    create_element("Memory of Important Events","Memória de Eventos Importantes",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Memory_of_Important_Events"})
    create_element("Meta Games","Meta Games",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Meta_Games"})
    create_element("Meta Servers","Meta Servidor",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Meta_Servers"})
    create_element("Meta-Postures","Meta-Posturas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Meta-Postures"})
    create_element("Meta-Techniques","Meta-Técnicas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Meta-Techniques"})
    create_element("Middlegame","Meio do Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Middlegame"})
    create_element("Mimetic Interfaces","Interfaces Miméticas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Mimetic_Interfaces"})
    create_element("Mini-maps","Mini-mapas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Mini-maps"})
    create_element("Minigames","Minijogos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Minigames"})
    create_element("Minimalized Social Weight","Peso Social Minimalizado",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Minimalized_Social_Weight"})
    create_element("Misfortune Mitigation","Mitigação de Infortúnio",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Misfortune_Mitigation"})
    create_element("Moveable Tiles","Ladrilhos Móveis",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Moveable_Tiles"})
    create_element("Movement","Movimentação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Movement"})
    create_element("Movement Limitations","Limitações em Movimentação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Movement_Limitations"})
    create_element("Mules","Mules",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Mules"})
    create_element("Mutual FUBAR Enjoyment","Apreciação Mútua de Tensão",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Mutual_FUBAR_Enjoyment"})
    create_element("Mutual Goals","Objetivos Mútuos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Mutual_Goals"})
    create_element("Narration Structures","Estruturas de Narração",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Narration_Structures"})
    create_element("Near Miss Indicators","Indicador de Quase Acerto",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Near_Miss_Indicators"})
    create_element("Negative Feedback Loops","Laços de Feedback Negativo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Negative_Feedback_Loops"})
    create_element("Negotiable Game Instance Duration","Ducação Negociável de Instância de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Negotiable_Game_Instance_Duration"})
    create_element("Negotiable Game Sessions","Sessão Negociável de Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Negotiable_Game_Sessions"})
    create_element("Negotiable Play Sessions","Sessão Negociável de Jogada",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Negotiable_Play_Sessions"})
    create_element("New Abilities","Novas Habilidades",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/New_Abilities"})
    create_element("Ninja Looting","Ninja Looting",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Ninja_Looting"})
    create_element("No Direct Player Influence","Sem Influência Direta do Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/No_Direct_Player_Influence"})
    create_element("No-Ops","Passar",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/No-Ops"})
    create_element("No-Use Bonus","Bônus de Não Uso",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/No-Use_Bonus"})
    create_element("Non-Consistent Narration","Narração Não Consistente",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Non-Consistent_Narration"})
    create_element("Non-Diegetic Communication","Comunicação Não Diegética",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Non-Diegetic_Communication"})
    create_element("Non-Diegetic Features","Características Não Diegéticas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Non-Diegetic_Features"})
    create_element("Non-Localized Resources","Recursos Não Localizados",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Non-Localized_Resources"})
    create_element("Non-Player Characters","Personagens Não Jogadores",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Non-Player_Characters"})
    create_element("Non-Player Help","Ajuda de Não Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Non-Player_Help"})
    create_element("Non-Renewable Resources","Recursos Não Renováveis",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Non-Renewable_Resources"})
    create_element("Obstacles","Obstáculos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Obstacles"})
    create_element("Open Destiny","Destino Aberto",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Open_Destiny"})
    create_element("Open-Ended Die Rolls","Rolagem de Dados de Repetição",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Open-Ended_Die_Rolls"})
    create_element("Optional Rules","Regras Opcionais",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Optional_Rules"})
    create_element("Orthogonal Differentiation","Diferenciação Ortogonal",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Orthogonal_Differentiation"})
    create_element("Outcome Indicators","Indicadores de Resultado",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Outcome_Indicators"})
    create_element("Own Agenda","Agenda Pessoal",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Own_Agenda"})
    create_element("Parallel Lives","Vidas Paralelas",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Parallel_Lives"})
    create_element("Parties","Partidos",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Parties"})
    create_element("Password Save Files","Arquivos Criptografados",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Password_Save_Files"})
    create_element("Pay to Play","Pay to Play",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Pay_to_Play"})
    create_element("Penalties","Pênaltis",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Penalties"})
    create_element("Performance Uncertainty","Incerteza de Realização",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Performance_Uncertainty"})
    create_element("Permadeath","Morte Permanente",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Permadeath"})
    create_element("Persistent Game World Changes","Mudanças Persistentes no Mundo do Jogo",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Persistent_Game_World_Changes"})
    create_element("Persistent Game Worlds","Mundo de Jogo Persistente",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Persistent_Game_Worlds"})
    create_element("Pervasive Gameplay","Jogabilidade Pervasiva",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Pervasive_Gameplay"})
    create_element("Phasing","Phasing",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Phasing"})
    create_element("Physical Enactment","Atuação Física",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Physical_Enactment"})
    create_element("Physical Navigation","Navegação Física",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Physical_Navigation"})
    create_element("Pick-Ups","Pick-Ups",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Pick-Ups"})
    create_element("Picture-in-Picture Views","Picture-in-Picture Views",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Picture-in-Picture_Views"})
    create_element("Player Agency","Agência do Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player_Agency"})
    create_element("Player Aids","Auxílio ao Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player_Aids"})
    create_element("Player Anonymity","Anonimidade de Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player_Anonymity"})
    create_element("Player Augmentations","Melhorias de Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player_Augmentations"})
    create_element("Player Balance","Balanceamento de Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player_Balance"})
    create_element("Player Characters","Personagem Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player_Characters"})
    create_element("Player Created Game Elements","Elementos Criado por Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player_Created_Game_Elements"})
    create_element("Player Elimination","Eliminação de Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player_Elimination"})
    create_element("Player Kicking","Expulsão de Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player_Kicking"})
    create_element("Player Killing","Superação de Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player_Killing"})
    create_element("Player Physical Prowess","Proesa Física de Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player_Physical_Prowess"})
    create_element("Player Unpredictability","Imprevisibilidade do Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player_Unpredictability"})
    create_element("Player-Artifact Proximity","Proximidade Jogador-Artefato",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player-Artifact_Proximity"})
    create_element("Player-Avatar Proximity","Proximidade Jogador-Avatar",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player-Avatar_Proximity"})
    create_element("Player-Created Characters","Personagens Criados por Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player-Created_Characters"})
    create_element("Player-Defined Goals","Objetivos Definidos pelo Jogador",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player-Defined_Goals"})
    create_element("Player-Location Proximity","Proximidade Jogador-Localização",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player-Location_Proximity"})
    create_element("Player-Planned Development","Desenvolvimento PLanejado ao Jogador", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player-Planned_Development"})
    create_element("Player-Player Proximity","Proximidade Jogador-Jogador", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player-Player_Proximity"})
    create_element("Player/Character Awareness Consistency","Consistência de Ciência Jogador/Personagem", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player/Character_Awareness_Consistency"})
    create_element("Player/Character Skill Composites","Composições de Habilidades Jogador/Personagem", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Player/Character_Skill_Composites"})
    create_element("Playing to Lose","Jogar para Perder", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Playing_to_Lose"})
    create_element("Point of Interest Indicators","Indicadores de Pontos de Interesse", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Point_of_Interest_Indicators"})
    create_element("Polyathlons","Polyathlons", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Polyathlons"})
    create_element("Positive Feedback Loops","Laços de Feedback Positivo", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Positive_Feedback_Loops"})
    create_element("Possibility of Anonymity","Possibilidade de Anonimidade", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Possibility_of_Anonymity"})
    create_element("Possibility of Graceful Surrender","Possibilidade de Rendição Branda", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Possibility_of_Graceful_Surrender"})
    create_element("Pottering","Pottering", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Pottering"})
    create_element("Power-Ups","Power-Ups", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Power-Ups"})
    create_element("Predefined Goals","Objetivos Predefinidos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Predefined_Goals"})
    create_element("Predetermined Story Structures","Estruturas Predeterminada de História", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Predetermined_Story_Structures"})
    create_element("Predictable Consequences","Consequências Previsíveis", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Predictable_Consequences"})
    create_element("Predictable Winner","Vencedor Previsível", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Predictable_Winner"})
    create_element("Preventing Goals","Impedimentos de Objetivos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Preventing_Goals"})
    create_element("Private Game Spaces","Espaço de Jogo Privado", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Private_Game_Spaces"})
    create_element("Privileged Abilities","Habilidades Privilegiadas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Privileged_Abilities"})
    create_element("Privileged Movement","Movimento Privilegiado", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Privileged_Movement"})
    create_element("Procedurally Generated Game Worlds","Mundo Procedural", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Procedurally_Generated_Game_Worlds"})
    create_element("Progress Indicators","Indicadores de Progresso", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Progress_Indicators"})
    create_element("Prompting Techniques","Prompting Techniques", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Prompting_Techniques"})
    create_element("Props","Props", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Props"})
    create_element("Public Player Statistics","Estatísticas Públicas de Jogador", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Public_Player_Statistics"})
    create_element("Purchasable Game Advantages","Vantagens de Jogo Compradas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Purchasable_Game_Advantages"})
    create_element("Puzzle Solving","Resolução de Puzzle", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Puzzle_Solving"})
    create_element("PvE","PvE", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/PvE"})
    create_element("PvP","PvP", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/PvP"})
    create_element("Quests","Quests",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Quests"})
    create_element("Quick Returns","Retornos Rápidos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Quick_Returns"})
    create_element("Quick Time Events","Quick Time Events", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Quick_Time_Events"})
    create_element("Quick Travel","Viagem Rápida", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Quick_Travel"})
    create_element("Quizzes","Quizzes", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Quizzes"})
    create_element("Rabbit Hole Invitations","Rabbit Hole Invitations",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Rabbit_Hole_Invitations"})
    create_element("Races","Corridas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Races"})
    create_element("Ragequitting","Ragequitting", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Ragequitting"})
    create_element("Real Life Activities Affect Game State","Estado do Jogo Afetado por Atividades Reais", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Real_Life_Activities_Affect_Game_State"})
    create_element("Real World Gameplay Spaces","Espaço de Jogabilidade no Mundo Real", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Real_World_Gameplay_Spaces"})
    create_element("Real World Knowledge Advantages","Vantagens de Conhecimento do Mundo Real", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Real_World_Knowledge_Advantages"})
    create_element("Real-Time Games","Jogos em Tempo Real", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Real-Time_Games"})
    create_element("Reconfigurable Game Worlds","Mundo de Jogo Reconfigurável", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Reconfigurable_Game_Worlds"})
    create_element("Reconnaissance","Reconhecimento", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Reconnaissance"})
    create_element("Red Herrings","Distrações", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Red_Herrings"})
    create_element("Regenerating Resources","Recursos Regenerativos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Regenerating_Resources"})
    create_element("Renewable Resources","Recursos Renováveis", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Renewable_Resources"})
    create_element("Repeat Combos","Combos de Repetição", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Repeat_Combos"})
    create_element("Repetition of Position Draws","Empate por Repetição de Posição", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Repetition_of_Position_Draws"})
    create_element("Repetitive Gameplay","Jogabilidade Repetitiva", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Repetitive_Gameplay"})
    create_element("Replayability","Rejogabilidade", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Replayability"})
    create_element("Replays","Replays", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Replays"})
    create_element("Rescue","Resgate", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Rescue"})
    create_element("Reserves","Reservas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Reserves"})
    create_element("Resource Caps","Capacidade de Recurso", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Resource_Caps"})
    create_element("Resource Competition","Competição por Recursos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Resource_Competition"})
    create_element("Resource Locations","Localizações de Recursos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Resource_Locations"})
    create_element("Resource Sources","Fontes de Recurso", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Resource_Sources"})
    create_element("Resources","Recursos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Resources"})
    create_element("Revoke Rules","Revogação de Regras", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Revoke_Rules"})
    create_element("Reward Widgets","Recompensas Extradiegéticas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Reward_Widgets"})
    create_element("Rewards","Recompensas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Rewards"})
    create_element("Rhythm-Based Actions","Ações Baseadas em Rítmo", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Rhythm-Based_Actions"})
    create_element("Robotic Players","Jogadores Robôs", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Robotic_Players"})
    create_element("Role Fulfillment","Cumprimento de Papel", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Role_Fulfillment"})
    create_element("Role Selection","Seleção de Papel", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Role_Selection"})
    create_element("Roleplaying","Interpretação de Papel", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Roleplaying"})
    create_element("Safe Havens","Refúgios",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Safe_Havens"})
    create_element("Sanctioned Cheating","Trapaça Permitida", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Sanctioned_Cheating"})
    create_element("Save Files","Save Files", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Save_Files"})
    create_element("Save Points","Save Points", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Save_Points"})
    create_element("Save Scumming","Trapaça por Save", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Save_Scumming"})
    create_element("Save-Load Cycles","Ciclos de Save-Load", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Save-Load_Cycles"})
    create_element("Scenes","Cenas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Scenes"})
    create_element("Score Tracks","Marcador de Score", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Score_Tracks"})
    create_element("Scores","Scores", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Scores"})
    create_element("Scouting","fazer reconhecimento", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Scouting"})
    create_element("Scripted Information Sequences","Sequências de Formação Predefinidas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Scripted_Information_Sequences"})
    create_element("Seamful Gameplay","Jogabilidade Viesada", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Seamful_Gameplay"})
    create_element("Secondary Interface Screens","Tela de Interface Secundária", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Secondary_Interface_Screens"})
    create_element("Secret Areas","Áreas Secretas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Secret_Areas"})
    create_element("Secret Goals","Objetivos Secretos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Secret_Goals"})
    create_element("Secret Resources","Recursos Secretos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Secret_Resources"})
    create_element("Secret Scoring Mechanisms","Mecanismos Secretos de Score", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Secret_Scoring_Mechanisms"})
    create_element("Selectable Set of Goals","Conjunto de Objetivos Selecionáveis", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Selectable_Set_of_Goals"})
    create_element("Self-Facilitated Games","Jogo Auto-Arbitrado", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Self-Facilitated_Games"})
    create_element("Self-Reported Positioning","Posicionamento Auto-Reportado", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Self-Reported_Positioning"})
    create_element("Self-Service Kiosks","Kiosques de Auto-Serviço", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Self-Service_Kiosks"})
    create_element("Sense of Self","Senso do Self", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Sense_of_Self"})
    create_element("Setback Penalties","Penalidades Impeditivas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Setback_Penalties"})
    create_element("Sets","COnjuntos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Sets"})
    create_element("Shared Penalties","Penalidades Compartilhadas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Shared_Penalties"})
    create_element("Shared Resources","Recursos Compartilhados", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Shared_Resources"})
    create_element("Shared Rewards","Recompensas Compartilhadas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Shared_Rewards"})
    create_element("Shrinking Game Worlds","Encolhimento do Mundo de Jogo", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Shrinking_Game_Worlds"})
    create_element("Sidegrades","Sidegrades", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Sidegrades"})
    create_element("Sidequests","Sidequests", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Sidequests"})
    create_element("Single-Player Games","Jogo Single Player", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Single-Player_Games"})
    create_element("Skills","Perícias", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Skills"})
    create_element("Sniper Locations","Localidade de Sniper", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Sniper_Locations"})
    create_element("Social Adaptability","Adaptabilidade Social", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Social_Adaptability"})
    create_element("Social Dilemmas","Dilemas Sociais", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Social_Dilemmas"})
    create_element("Social Rewards","Recompensas Sociais", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Social_Rewards"})
    create_element("Social Roles","Papéis Socials", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Social_Roles"})
    create_element("Social Skills","Perícias Sociais", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Social_Skills"})
    create_element("Sockets","Sockets", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Sockets"})
    create_element("Solution Uncertainty","Incerteza da Solução", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Solution_Uncertainty"})
    create_element("Spawning","Desova", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Spawning"})
    create_element("Spectacular Failure Enjoyment","Apreciação de Falha", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Spectacular_Failure_Enjoyment"})
    create_element("Spectators","Espectadores", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Spectators"})
    create_element("Speedending","Speedending", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Speedending"})
    create_element("Speedruns","Speedruns", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Speedruns"})
    create_element("Split-Screen Views","Visões em Tela Separada", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Split-Screen_Views"})
    create_element("Stack Seeding","Manipulação da Aleatoriedade", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Stack_Seeding"})
    create_element("Startgame","Início de Jogo", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Startgame"})
    create_element("Steadily Decreasing Resources","Decrescimento Acelerado de Recursos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Steadily_Decreasing_Resources"})
    create_element("Stealth","Furtividade", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Stealth"})
    create_element("Stimulated Planning","Planejamento Estimulado", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Stimulated_Planning"})
    create_element("Storytelling","Storytelling", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Storytelling"})
    create_element("Strategic Knowledge","Conhecimento Estratégico", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Strategic_Knowledge"})
    create_element("Strategic Locations","Localizações Estratégicas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Strategic_Locations"})
    create_element("Strategic Planning","Planejamento Estratégico", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Strategic_Planning"})
    create_element("Substitute Actions","Ações Substitutas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Substitute_Actions"})
    create_element("Summary Updates","Resumo de Atualizações", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Summary_Updates"})
    create_element("Supporting Goals","Objetivos de Suporte", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Supporting_Goals"})
    create_element("Surprise Attacks","Ataques Surpresa", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Surprise_Attacks"})
    create_element("Surrendering","Rendição", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Surrendering"})
    create_element("Sustenance Rewards","Recompensas de Sustentos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Sustenance_Rewards"})
    create_element("Switches","Chaves", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Switches"})
    create_element("Symbiotic Player Relations","Relações Simbióticas entre Jogadores", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Symbiotic_Player_Relations"})
    create_element("Symmetric Goals","Objetivos Simétricos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Symmetric_Goals"})
    create_element("Synchronous Gameplay","Jogabilidade Síncrona", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Synchronous_Gameplay"})
    create_element("Tactical Planning","Planejamento Tático",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Tactical_Planning"})
    create_element("Team Accomplishments","Alcances de Time", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Team_Accomplishments"})
    create_element("Team Balance","Balanceamento de Time", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Team_Balance"})
    create_element("Team Combos","Combos de Time", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Team_Combos"})
    create_element("Team Development","Desenvolvimento de Time", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Team_Development"})
    create_element("Team Elimination","Eliminação de Time", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Team_Elimination"})
    create_element("Team Strategy Identification","Identificação de Estratégia de Time", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Team_Strategy_Identification"})
    create_element("Teams","Times", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Teams"})
    create_element("Temporal Consistency","Consistência Temporal", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Temporal_Consistency"})
    create_element("Temporary Abilities","Habilidades Temporais", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Temporary_Abilities"})
    create_element("Tension","Tensão", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Tension"})
    create_element("Territories","Territórios", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Territories"})
    create_element("Testing Achievements","Alcances de Teste", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Testing_Achievements"})
    create_element("Thematic Consistency","Consistência Temática", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Thematic_Consistency"})
    create_element("Third-Person Views","Visão em Terceira Pessoa", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Third-Person_Views"})
    create_element("Tick-Based Games","Jogos Baseados em Ticks", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Tick-Based_Games"})
    create_element("Tiebreakers","Regra de Desempate", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Tiebreakers"})
    create_element("Tied Results","Resultados de Empate", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Tied_Results"})
    create_element("Tiered Participation","Participação em Camadas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Tiered_Participation"})
    create_element("Tile-Laying","Colocação de Ladrilhos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Tile-Laying"})
    create_element("Tiles","Ladrilhos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Tiles"})
    create_element("Time Limited Game Instances","Instância de Jogo com Limite de Tempo", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Time_Limited_Game_Instances"})
    create_element("Time Limits","Limite de Tempo", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Time_Limits"})
    create_element("Time Pressure","Pressão por Tempo", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Time_Pressure"})
    create_element("Togetherness","União", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Togetherness"})
    create_element("Token Placement","Colocação de Tokens", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Token_Placement"})
    create_element("Tools","Ferramentas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Tools"})
    create_element("Tooltips","Informações Localizadas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Tooltips"})
    create_element("Traces","Rastros", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Traces"})
    create_element("Trade-Offs","Decisões", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Trade-Offs"})
    create_element("Transferable Items","Itens Transferíveis", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Transferable_Items"})
    create_element("Transport Routes","Rotas de Transporte", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Transport_Routes"})
    create_element("Traps","Armadilhas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Traps"})
    create_element("Trial and Error Solutions","Soluções por Tentativa e Erro", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Trial_and_Error_Solutions"})
    create_element("Trick Taking","Trick Taking", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Trick_Taking"})
    create_element("Trumps","Trunfos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Trumps"})
    create_element("Turn Taking","Reaização de Turno", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Turn_Taking"})
    create_element("Turn-Based Games","Jogo Baseado em Turnos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Turn-Based_Games"})
    create_element("Turnovers","Fim de Turno", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Turnovers"})
    create_element("TvT","Time vs Time", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/TvT"})
    create_element("Ubiquitous Gameplay","Jogabilidade Ubíqua",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Ubiquitous_Gameplay"})
    create_element("Ultra-Powerful Events","Eventos Ultra-Poderosos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Ultra-Powerful_Events"})
    create_element("Uncertainty of Information","Incerteza de Informação", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Uncertainty_of_Information"})
    create_element("Uncertainty of Outcome","Incerteza de Resultado", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Uncertainty_of_Outcome"})
    create_element("Units","Unidades", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Units"})
    create_element("Unknown Goals","Objetivos Desconhecidos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Unknown_Goals"})
    create_element("Unlocking","Destravar", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Unlocking"})
    create_element("Unpredictable Behavior","Comportamento Imprevisível", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Unpredictable_Behavior"})
    create_element("Unsynchronized Game Sessions","Sessões de Jogo Não Sincronizadas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Unsynchronized_Game_Sessions"})
    create_element("Unwinnable Game States","Estados de Jogo Não Vencíveis", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Unwinnable_Game_States"})
    create_element("Unwinnable Games","Jogos Não Vencíveis", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Unwinnable_Games"})
    create_element("Upgrades","Upgrades", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Upgrades"})
    create_element("Value of Effort","Valor do Esforço",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Value_of_Effort"})
    create_element("Variable Accuracy","Precisão Variável", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Variable_Accuracy"})
    create_element("Varied Gameplay","Jogabilidade Variável", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Varied_Gameplay"})
    create_element("Varying Rule Sets","Conjunto de Regras Variáveis", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Varying_Rule_Sets"})
    create_element("Varying Turn Orders","Ordem de Turno Variáveis", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Varying_Turn_Orders"})
    create_element("Vehicle Sections","Seções de Veículo", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Vehicle_Sections"})
    create_element("Vehicles","Veículos", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Vehicles"})
    create_element("Vision Modes","Modos de Visão", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Vision_Modes"})
    create_element("Vulnerabilities","Vulnerabilidades", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Vulnerabilities"})
    create_element("Warming-Up Roleplay Exercises","Exercícios de Aquecimento de Atuação",{"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Warming-Up_Roleplay_Exercises"})
    create_element("Warp Zones","Zonas de Transporte", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Warp_Zones"})
    create_element("Weapons","Armas", {"type":"single","source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Weapons"})
    create_element("Winner determined after Gameplay Ends","Vencedor Definido Após Termino de Jogo",{"type":"single", "source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Winner_determined_after_Gameplay_Ends"})
    create_element("Winning by Ending Gameplay","Vencimento por Finalizar Jogo",{"type":"single", "source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Winning_by_Ending_Gameplay"})
    create_element("Workshopping","Ações de Oficina",{"type":"single", "source":"link","ref":"/iex.php/Workshopping"})
    create_element("Zero-Player Games","Jogos sem jogadores",{"type":"single", "source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Zero-Player_Games"})
    create_element("Zone of Control","Zona de Controle",{"type":"single", "source":"link","ref":"http://virt10.itu.chalmers.se/index.php/Zone_of_Control"})
